name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '14.x'
      
      - uses: actions/checkout@v2
      - run: |
          npm ci
          npm run build
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: Dockerfile
          tags: isurabuy/user-manager-pro-app:${{github.run_id}}
          
      - name: Run the version update script
        env:
          TOKEN: ${{secrets.USER_PAT}}
          RELEASE_ID: ${{github.run_id}}
        run: bash version-update.sh iit-bot $TOKEN $GITHUB_WORKSPACE $RELEASE_ID
        id: version_bump_fe
